-- Give App Database Schema

CREATE DATABASE IF NOT EXISTS give_db;
USE give_db;

-- Users table
CREATE TABLE IF NOT EXISTS users (
  id VARCHAR(21) PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  name VARCHAR(255),
  avatar VARCHAR(255),
  google_id VARCHAR(255) UNIQUE,
  verified BOOLEAN DEFAULT FALSE,
  created DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Givings table
CREATE TABLE IF NOT EXISTS givings (
  id VARCHAR(21) PRIMARY KEY,
  user_id VARCHAR(21) NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  type ENUM('offering', 'tithe', 'pledge') NOT NULL,
  date DATE NOT NULL,
  description VARCHAR(255),
  created DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
